# Generated by Django 5.1.2 on 2024-10-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleimage',
            name='detected_plate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
