# Generated by Django 5.1.2 on 2024-10-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_app', '0002_alter_vehicleimage_detected_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimage',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_plates/'),
        ),
    ]
